package br.com.lucasmoraes.magosupremo;

import android.app.Activity;
import android.app.AlertDialog;
import android.os.Bundle;
import android.text.InputType;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import android.database.Cursor;
import br.com.lucasmoraes.magosupremo.database.GameDatabase;
import br.com.lucasmoraes.magosupremo.battle.CombatEngine;
import br.com.lucasmoraes.magosupremo.admin.CommandProcessor;

public class MainActivity extends Activity {
    private GameDatabase db; private TextView profile,resources; private boolean adminAuthenticated=false;
    @Override public void onCreate(Bundle state){super.onCreate(state);setContentView(R.layout.activity_main);db=new GameDatabase(this);profile=findViewById(R.id.profile);resources=findViewById(R.id.resources);
        findViewById(R.id.createAccount).setOnClickListener(v->createAccount());findViewById(R.id.collection).setOnClickListener(v->showCollection());findViewById(R.id.openPack).setOnClickListener(v->openPack());findViewById(R.id.battle).setOnClickListener(v->battle());findViewById(R.id.missions).setOnClickListener(v->showMissions());findViewById(R.id.admin).setOnClickListener(v->admin());findViewById(R.id.about).setOnClickListener(v->about());refresh();}
    private void refresh(){int id=db.activeId();if(id<0){profile.setText("Viajante • crie sua conta para começar");resources.setText("🪙 0 moedas     🔮 0 cristais");return;}Cursor c=db.account(id);if(c.moveToFirst()){profile.setText("✦ "+c.getString(1)+" • ID "+String.format(java.util.Locale.ROOT,"%06d",id)+" • Nível "+c.getInt(2));resources.setText("🪙 "+c.getInt(4)+" moedas     🔮 "+c.getInt(5)+" cristais");}c.close();}
    private void createAccount(){EditText input=new EditText(this);input.setHint("Seu nickname (3–16 caracteres)");new AlertDialog.Builder(this).setTitle("Criar conta de mago").setMessage("A conta é salva neste aparelho.").setView(input).setNegativeButton("Cancelar",null).setPositiveButton("Criar",(d,w)->{try{int id=db.createAccount(input.getText().toString());db.setActive(id);db.grantCard(id,1000,1);db.log(id,"BOAS_VINDAS","Carta inicial concedida");toast("Conta criada! Seu ID é "+String.format(java.util.Locale.ROOT,"%06d",id));refresh();}catch(Exception e){alert("Não foi possível criar a conta",e.getMessage());}}).show();}
    private void showCollection(){int id=db.activeId();if(id<0){toast("Crie uma conta primeiro.");return;}Cursor c=db.collection(id);StringBuilder s=new StringBuilder();while(c.moveToNext())s.append("✦ ").append(c.getString(1)).append(" ×").append(c.getInt(6)).append("\n").append(c.getString(2)).append(" • ").append(c.getString(3)).append(" • ATQ ").append(c.getInt(4)).append(" DEF ").append(c.getInt(5)).append("\n").append(c.getString(7)).append("\nHabilidade: ").append(c.getString(8)).append("\n\n");c.close();if(s.length()==0)s.append("Seu grimório está vazio. Abra um pacote para encontrar cartas.");new AlertDialog.Builder(this).setTitle("Coleção • "+db.countCards()+" cartas no mundo").setMessage(s.toString()).setPositiveButton("Fechar",null).show();}
    private void openPack(){int id=db.activeId();if(id<0){toast("Crie uma conta primeiro.");return;}if(!db.openPack(id)){toast("Você precisa de 100 moedas para abrir um pacote.");return;}Cursor c=db.collection(id);String last="Uma carta entrou no seu grimório!";while(c.moveToNext())last="Você possui "+c.getInt(6)+" × "+c.getString(1)+"\nRaridade: "+c.getString(2)+"\nElemento: "+c.getString(3);c.close();refresh();alert("✨ PACOTE ABERTO!",last);}
    private void battle(){int id=db.activeId();if(id<0){toast("Crie uma conta primeiro.");return;}Cursor c=db.collection(id);int attack=10,defense=5;String name="Aprendiz do Véu";if(c.moveToFirst()){name=c.getString(1);attack=c.getInt(4);defense=c.getInt(5);}c.close();CombatEngine engine=new CombatEngine();CombatEngine.Fighter player=new CombatEngine.Fighter(100,attack,defense,5),enemy=new CombatEngine.Fighter(70,22,8,5);StringBuilder log=new StringBuilder("Sua carta: "+name+"\n\n");int turns=0;while(player.hp>0&&enemy.hp>0&&turns<10){int dealt=engine.damage(player,enemy,3);log.append("Você causou ").append(dealt).append(" de dano. Inimigo: ").append(enemy.hp).append(" HP.\n");if(enemy.hp>0){int received=engine.damage(enemy,player,0);log.append("O inimigo causou ").append(received).append(" de dano. Você: ").append(player.hp).append(" HP.\n");}player.energy=Math.max(1,player.energy);enemy.energy=Math.max(1,enemy.energy);turns++;}boolean win=enemy.hp<=0;if(win){db.addCurrency(id,"coins",75);db.log(id,"BATALHA_VITORIA","Recompensa: 75 moedas");}else db.log(id,"BATALHA_DERROTA","Batalha rápida");refresh();alert(win?"🏆 VITÓRIA!":"⚔️ FIM DA BATALHA",log+"\n"+(win?"Você recebeu 75 moedas.":"Treine suas cartas e tente novamente."));}
    private void showMissions(){int id=db.activeId();if(id<0){toast("Crie uma conta primeiro.");return;}String s="MISSÕES DO VÉU\n\n• Crie sua conta — concluída\n• Abra seu primeiro pacote — abra um pacote\n• Vença uma batalha — recompensa de 75 moedas\n• Colecione cartas — continue explorando\n\nAs missões e recompensas avançam conforme os sistemas são ampliados.";alert("Missões",s);}
    private void admin(){if(!db.adminConfigured()){EditText p=new EditText(this);p.setHint("Crie uma senha forte (mín. 8 caracteres)");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Configurar ADMIN MASTER").setMessage("Esta senha será configurada neste aparelho. Não a esqueça; não existe recuperação remota.").setView(p).setNegativeButton("Cancelar",null).setPositiveButton("Configurar",(d,w)->{try{db.configureAdmin(p.getText().toString().toCharArray());adminAuthenticated=true;adminConsole();}catch(Exception e){alert("Erro",e.getMessage());}}).show();return;}EditText p=new EditText(this);p.setHint("Senha do administrador");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Autenticação ADMIN MASTER").setView(p).setNegativeButton("Cancelar",null).setPositiveButton("Entrar",(d,w)->{if(db.verifyAdmin(p.getText().toString().toCharArray())){adminAuthenticated=true;adminConsole();}else toast("Senha incorreta.");}).show();}
    private void adminConsole(){EditText cmd=new EditText(this);cmd.setHint("/adminhelp");new AlertDialog.Builder(this).setTitle("ADMIN MASTER • local").setMessage("Comandos não executam SQL nem comandos do sistema.").setView(cmd).setNegativeButton("Fechar",null).setPositiveButton("Executar",(d,w)->{String result=new CommandProcessor(db).execute(cmd.getText().toString(),adminAuthenticated);alert("Resultado",result);refresh();}).show();}
    private void about(){alert("MAGO SUPREMO","Atravesse portais, descubra relíquias e construa seu grimório em um universo de fantasia sombria. Colecione cartas arcanas, evolua seus poderes e enfrente desafios rumo ao título de Mago Supremo e Soberano do Véu.\n\nO jogo funciona offline e salva o progresso neste aparelho. Esta versão inicial está em desenvolvimento.\n\nCriado por Lucas Moraes");}
    private void alert(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
